name: build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Gradle
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: testDebugUnitTest